### ISSUE TITLE
An example for REST APIs

### ISSUE THREAD

**Issue by gustavonobreza** [hiro1107/nestjs-supabase-auth#1]
#### Can you add an exemple for a REST API, please?
I got confused trying to use your lib on a personal project. Can you help me?
I'm having trouble understanding some NestJS concepts while studying authentication and encryption.
### 😄

**Comment by Aldo111** [comment]
Curious if you ended up getting through it, @gustavonobreza? If not, I can share an example soon as I'm integrating this into my NestJS + React stack so that I can ensure certain routes are protected and get user id data.

**Comment by gustavonobreza** [comment]
Thanks @Aldo111
Would you really do this?

I would be very grateful 😁
How we can share the same repo? Email (zipper file) ?

**Comment by Aldo111** [comment]
I can't share my full repo as my project is private but here's essentially a more guided version of the Readme/tutorial to do basic authentication + route guarding using this package.

1. Make a new folder/module called `auth`, just to group this stuff under.

2. Create a new strategy using supabase (eg. `auth_supabase.strategy.ts` or `supabase.strategy.ts` or w/e), just like they show in the readme with a minor change - in the `validate` function, make sure you **RETURN** the data being validated. You can pretty much copy paste the following:

```
import { Injectable } from '@nestjs/common';
import { PassportStrategy } from '@nestjs/passport';
import { ExtractJwt } from 'passport-jwt';
import { SupabaseAuthStrategy, SupabaseAuthUser } from 'nestjs-supabase-auth';

@Injectable()
export class SupabaseStrategy extends PassportStrategy(
  SupabaseAuthStrategy,
  'supabase',
) {
  public constructor() {
    super({
      supabaseUrl: process.env.SUPABASE_URL,
      supabaseKey: process.env.SUPABASE_KEY,
      supabaseOptions: {},
      supabaseJwtSecret: process.env.SUPABASE_JWT_SECRET,
      extractor: ExtractJwt.fromAuthHeaderAsBearerToken(),
    });
  }

  async validate(payload: any): Promise<SupabaseAuthUser> {
    const user = await super.validate(payload);
    return user;
  }

  authenticate(req) {
    super.authenticate(req);
  }
}
```

By returning the `user` in the `validate` method, you allow the `user` object from the JWT token to be extracted, verified (this is what this repo's underyling passport strategy does), and puts it in the HTTP request context so that you can use it in your API routes.

FYI, your auth.module.ts should now look like this:
```
import { Module } from '@nestjs/common';
import { SupabaseStrategy } from './supabase.strategy';
import { PassportModule } from '@nestjs/passport';

@Module({
  imports: [PassportModule],
  providers: [SupabaseStrategy],
  exports: [SupabaseStrategy],
})
export class AuthModule {}
```

3. Create a UserId decorator (user_id.decorator.ts) like the one in the readme but do it as follows if you're not doing it for GraphQL purposes (for example, all I wanted was to have access to the current request's user ID within my API routes/controller methods so I could do more user-specific stuff).

```
import { createParamDecorator, ExecutionContext } from '@nestjs/common';

export const UserId = createParamDecorator(
  (_data: unknown, context: ExecutionContext) => {
    return context.switchToHttp().getRequest()?.user?.id;
  },
);
```

4. Now, in any of your API routes that you want to protect via auth (and optionally, have access to the UserId in the request params) use the supabase strategy you made:

```
@UseGuards(AuthGuard('supabase'))
@Post('create')
  public async createEntity(
    @Body() body: Entity,
    @UserId() userId: string,
  ): Promise<Pipeline> {
    // Do stuff with the `userId`, which is verified now to be correctly authenticated.
    body.createdBy = userId;
    console.log(body);
    return this.service.createEntity(body);
  }
```

---
In the clientside, you want to make sure you pass the session's `access_token` from supabase auth as a header on the HTTP request. The header should look like: `Authorization: Bearer <access_token, which is basically the JWT>`

**Comment by Aldo111** [comment]
Hope that helps @gustavonobreza

**Comment by gustavonobreza** [comment]
@Aldo111 thank you so much 😁
You really helped me!
